In [1]:
import numpy as np
import sklearn.datasets as ds
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import confusion_matrix

In [2]:
digits = ds.load_digits()
X = digits.data
y = digits.target.copy()

In [3]:
y[digits.target ==9 ] = 1
y[digits.target !=9 ] = 0

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=666)

In [5]:
log_res = LogisticRegression()
log_res.fit(X_train, y_train)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [6]:
y_test_predict = log_res.predict(X_test)

In [7]:
print("precisionScore:", precision_score(y_test, y_test_predict))
print("recallScore:", recall_score(y_test, y_test_predict))

precisionScore: 0.9473684210526315
recallScore: 0.8


In [8]:
confusion_matrix(y_test, y_test_predict)

array([[403,   2],
       [  9,  36]])

In [9]:
decision_score = log_res.decision_function(X_test)

In [10]:
decision_score.shape

(450,)

In [11]:
decision_score[:30]

array([-21.410194  , -32.8936381 , -16.38814108, -79.80821714,
       -48.04872851, -24.19617843, -44.58192386, -24.27422947,
        -1.13753574, -18.99724408, -65.81497264, -50.95760476,
       -30.94963068, -45.94581759, -37.36425466, -29.48151725,
       -36.94205258, -82.77234195, -37.5952222 ,  -9.89393948,
        -9.24963573, -85.21560948, -16.74129927, -45.35408892,
        -5.02386394, -48.26504739, -11.67040022, -37.39714733,
       -25.08726328, -13.60436382])

In [12]:
log_res.predict(X_test)[:30]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

### 逻辑回归 决策边界 θT ⋅xb =0
### θT ⋅xb = threshold

### decision_score >= 0 default

In [13]:
y_predict2 = np.array(decision_score >= 0 , dtype="int")

In [14]:
print("precisionScore:", precision_score(y_test, y_predict2))
print("recallScore:", recall_score(y_test, y_predict2))

precisionScore: 0.9473684210526315
recallScore: 0.8


### decision_score >= 5 

In [15]:
y_predict3 = np.array(decision_score >= 5 , dtype="int")

In [16]:
print("precisionScore:", precision_score(y_test, y_predict3))
print("recallScore:", recall_score(y_test, y_predict3))

precisionScore: 0.96
recallScore: 0.5333333333333333


In [17]:
confusion_matrix(y_test, y_predict3)

array([[404,   1],
       [ 21,  24]])

### decision_score >= -5 

In [18]:
y_predict4 = np.array(decision_score >= -5 , dtype="int")

In [19]:
print("precisionScore:", precision_score(y_test, y_predict4))
print("recallScore:", recall_score(y_test, y_predict4))

precisionScore: 0.7272727272727273
recallScore: 0.8888888888888888


In [20]:
confusion_matrix(y_test, y_predict4)

array([[390,  15],
       [  5,  40]])